[".oh-my-zsh"]
type = "archive"
url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
type = "archive"
url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
type = "archive"
url = "https://github.com/romkatv/powerlevel10k/archive/master.tar.gz"
exact = true
stripComponents = 1
refreshPeriod = "168h"

[".local/share/fonts/Firacode"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.4.0/FiraCode.tar.xz"
include = ["*.ttf"]

[".local/share/fonts/MapleMonoNR-NF-CN"]
type = "archive"
url = "https://github.com/eeepin/maple-font/releases/download/v1775278490/MapleMonoNR-NF-CN.zip"
include = ["*.ttf"]

[".local/share/fonts/MapleMonoNR-NF"]
type = "archive"
url = "https://github.com/eeepin/maple-font/releases/download/v1775278490/MapleMonoNR-NF.zip"
include = ["*.ttf"]
